








const object_customer= {
    customer_id : "",
    customer_title: "Mr",
    customer_type : "I",
    customer_first_name : "Sai Bhargav",
    customer_middle_name : "",
    customer_last_name : "Sankoji",
    customer_email : "saibhargav.sankoji@gmail.com",
    customer_mobile : 9666606228,
    customer_dob : "23/02/1997",
    customer_occupation : "Male",
    customer_marital_status : "Married",
    customer_occupation : "",
    customer_aadhar : 0,
    customer_pan : "JMUPS0123S",
    customer_passport : "",
    customer_voter_id : "",
    customer_city : "",
    customer_city_code : 0,
    customer_address_line1 : "",
    customer_address_line2 : "",
    customer_address_line3 : "",
    customer_pincode : 505327,
    customer_pincode_locality : "",
    customer_district : "",
    customer_district_code : 0,
    customer_state : "",
    customer_state_code : 0,
    customer_city : "",
    customer_premanent_city_code : 0,
    customer_premanent_address_line1 : "",
    customer_premanent_address_line2 : "",
    customer_premanent_address_line3 : "",
    customer_premanent_pincode : 505327,
    customer_premanent_pincode_locality : "",
    customer_premanent_district : "",
    customer_premanent_district_code : 0,
    customer_premanent_state : "",
    customer_premanent_state_code : 0,
    customer_crn_number : "",
    customer_gst_number : "",
    organization_name : "",
    organization_contact_name : "",
    organization_email : "",
    organization_mobile : "",
    organization_pincode : "",
    organization_address_line1 : "",
    organization_tan_number : "",
    organization_gst_number : ""
}

const input_details = {
    input_idv : "",
    input_vechile : "",
    input_rto : "",
    input_registration_date : "",
    input_policy_duration : 0,
    input_prev_policy_expire_date : "",
    input_policy_tenure : 0,
    input_electrical : 0,
    input_non_electrical : 0,
    input_bi_fuel : 0,
    input_no_clain_bonus : 0,
    input_voluntry_access : false,
    input_anti_theif_device : false,
    input_aa_membership : false,
    input_tppd : false,
    input_paid_driver : false,
    input_unnamed_passenger : false,
    input_paid_driver : false,
    input_addons : false
}

const tw_save_proposal_and_payment = {
    user_login_id : "",
    workflow_id : "",
    quote_id : "",
    nominee_name : "",
    nominee_dob : "",
    nominee_relationship : "",
    branch_inward_date : "Current Date",
    branch_inward_number : "",
    vechile_registration_number1 : "MH",
    vechile_registration_number2 : "01",
    vechile_registration_number1 : "KK",
    vechile_engine_number : "",
    vechile_chassis_number : "",
    previous_insurer_code : "",
    previous_insurer_policy_number : "",
    is_vechile_financed : false,
    is_valid_pucc : false,
    financer_address : "",
    financer_code : 0,
    financer_name : "",
}

const payment_details = {
    payment_account_number : "",
     payment_workflow_id : "",
     payment_quote_id : "",
     payment_proposal_id : "",
     payment_intermediate_code : "",
     payment_customer_id : "",
    payment_number : "",
     payment_instrument_no : "",
     payment_premium_amount : "",
     payment_instrument_amount : "", 
     payment_transaction_flag : "",
     payment_logged_in_user_id : "",
     payment_product_info : "",
}

const mainObject = {...input_details, ...object_customer, ...payment_details, ...tw_save_proposal_and_payment}
// const customer_details = {
//     title: "Mr",
//     type: "I",
//     first_name: "Sai Bhargav",
//     middle_name: "",
//     last_name: "Sankoji",
//     email: "saibhargav.sankoji@gmail.com",
//     mobile: 9666606228,
//     dob: "23/02/1997",
//     occupation: "Male",
//     marital_status: "Married",
//     occupation: "",
//     aadhar: 0,
//     pan: "JMUPS0123S",
//     passport: "",
//     voter_id: "",
//     city: "",
//     city_code: 0,
//     address_line1: "",
//     address_line2: "",
//     address_line3: "",
//     pincode: 505327,
//     pincode_locality: "",
//     district: "",
//     district_code: 0,
//     state: "",
//     state_code: 0,
//     city: "",
//     premanent_city_code: 0,
//     premanent_address_line1: "",
//     premanent_address_line2: "",
//     premanent_address_line3: "",
//     premanent_pincode: 505327,
//     premanent_pincode_locality: "",
//     premanent_district: "",
//     premanent_district_code: 0,
//     premanent_state: "",
//     premanent_state_code: 0,
//     crn_number: "",
//     gst_number: "",

// }
// const organization_details = {
//     name: "",
//     contact_name: "",
//     email: "",
//     mobile: "",
//     pincode: "",
//     address_line1: "",
//     tan_number: "",
//     gst_number: ""
// }
// const input_details = {
//     idv: "",
//     vechile: "",
//     rto: "",
//     registration_date: "",
//     policy_duration: 0,
//     prev_policy_expire_date: "",
//     policy_tenure: 0,
//     electrical: 0,
//     non_electrical: 0,
//     bi_fuel: 0,
//     no_clain_bonus: 0,
//     voluntry_access: false,
//     anti_theif_device: false,
//     aa_membership: false,
//     tppd: false,
//     paid_driver: false,
//     unnamed_passenger: false,
//     paid_driver: false,
//     addons: false
// }

// const propoal_details = {
//     user_login_id: "",
//     workflow_id: "",
//     quote_id: "",
//     nominee_name: "",
//     nominee_dob: "",
//     nominee_relationship: "",
//     branch_inward_date: "Current Date",
//     branch_inward_number: "",
//     vechile_registration_number1: "MH",
//     vechile_registration_number2: "01",
//     vechile_registration_number1: "KK",
//     vechile_engine_number: "",
//     vechile_chassis_number: "",
//     previous_insurer_code: "",
//     previous_insurer_policy_number: "",
//     is_vechile_financed: false,
//     is_valid_pucc: false,
//     financer_address: "",
//     financer_code: 0,
//     financer_name: "",
// }

// const payment_details = {
//     account_number: "",
//     workflow_id: "",
//     quote_id: "",
//     proposal_id: "",
//     intermediate_code: "",
//     customer_id: "",
//     payment_number: "",
//     instrument_no: "",
//     premium_amount: "",
//     instrument_amount: "",
//     transaction_flag: "",
//     logged_in_user_id: "",
//     product_info: "",
// }

// const mainObject = {
//     input_details,
//     customer_details,
//     organization_details,
//     propoal_details,
//     payment_details
// }

// const client_object = {
//     idv: "",
//     input_details: {
//         idv: "",
//         vechile: "",
//         rto: "",
//         registration_date: "",
//         policy_duration: "",
//         previous_policy_exp_date: "",
//         policy_tenure: "",
//         value_of_accessories: {
//             electrical: "",
//             non_electrical: "",
//             bi_fuel_kit: "",
//         },
//         discount: {
//             no_clam_bonus: 0,
//             voluntry_access: false,
//             anti_thief_device: false,
//             aa_membership: false,
//             tppd: false,
//         },
//         personal_accident_cover: {
//             paid_driver: false,
//             un_named_passenger: false,
//             paid_driver: false,
//         },
//         addons_coverage: {}
//     },
//     contact_details: {
//         title: "",
//         first_name: "",
//         last_name: "",
//         middle_name: "",
//         dob: "",
//         marital_status: "",
//         aadhar_number: "",
//         occupation: "",
//         gender: "",
//         gst_no: "",
//         mobile: 0,
//         email: "",
//         vechile_registration_address: {
//             address_line1: "",
//             address_line2: "",
//             address_line3: "",
//             pincode: 0,
//             city: "",
//             state: "",
//             locality: "",
//         },
//         communication_address: {
//             address_line1: "",
//             address_line2: "",
//             address_line3: "",
//             pincode: 0,
//             city: "",
//             state: "",
//             locality: "",
//         }
//     },
//     vechile_details: {
//         registration_no: "",
//         registration1: "TS",
//         registration2: "09",
//         registration3: "EA",
//         registration4: "1678",
//         engine_number: "",
//         chassis_number: "",
//         previous_policy_number: "",
//         is_financed: false,
//         is_valid_pucc: false,
//     },
//     nominee_details: {
//         nominee_relationship: "",
//         nominee_full_name: "",
//         nominee_dob: "",
//     }

// }


module.exports = mainObject